# **Import the libraries**

In [1]:
import numpy as np
import pandas as pd

# **Load the dataset**

In [3]:
df = pd.read_csv(r"C:\Users\Admin\Desktop\Machine Learning\Supervised Machine Learning\Regression\Linear Regression\Placement\placement.csv")

In [4]:
df.head(5)

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [5]:
df_10 = df.head(10)
df_10

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57
5  7.89     2.99
6  6.73     2.60
7  6.75     2.48
8  6.09     2.31
9  8.31     3.51